### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by PoilZero** [LeinneSW/PureEntities#46]
ImagicalMine Crash Dump Fri Mar 11 23:45:08 BNT 2016

Error: syntax error, unexpected ':', expecting ';' or '{'
File: /PureEntities-master/src/milk/pureentities/entity/monster/FlyingMonster
Line: 22
Type: E_PARSE

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[13] abstract class FlyingMonster extends FlyingEntity implements Monster{
[14] 
[15]     protected $attackDelay = 0;
[16] 
[17]     private $minDamage = [0, 0, 0, 0];
[18]     private $maxDamage = [0, 0, 0, 0];
[19] 
[20]     public abstract function attackEntity(Entity $player);
[21] 
[22]     public function getDamage(int $difficulty = null) : float{
[23]         return mt_rand($this->getMinDamage($difficulty), $this->getMaxDamage($difficulty));
[24]     }
[25] 
[26]     public function getMinDamage(int $difficulty = null) : float{
[27]         if($difficulty === null || $difficulty > 3 || $difficulty < 0){
[28]             $difficulty = Server::getInstance()->getDifficulty();
[29]         }
[30]         return $this->minDamage[$difficulty];
[31]     }
[32] 

Backtrace:
#0 /src/pocketmine/Server(0): pocketmine\Server->crashDump(boolean)
#1 /src/spl/BaseClassLoader(26): BaseClassLoader->loadClass(boolean)
#2 /src/spl/BaseClassLoader(26): spl_autoload_call(boolean)
#3 /src/spl/BaseClassLoader(128): (boolean)
#4 /src/pocketmine/entity/Entity(536): BaseClassLoader->loadClass(boolean)
#5 /src/pocketmine/entity/Entity(536): spl_autoload_call(boolean)
#6 /src/pocketmine/entity/Entity(536): ReflectionClass->__construct(boolean)
#7 /PureEntities-master/src/milk/pureentities/PureEntities(79): pocketmine\entity\Entity::registerEntity(boolean)
#8 /devtools插件.phar/src/FolderPluginLoader/FolderPluginLoader(73): milk\pureentities\PureEntities->onLoad(boolean)
#9 /devtools插件.phar/src/FolderPluginLoader/FolderPluginLoader(42): FolderPluginLoader\FolderPluginLoader->initPlugin(boolean)
#10 /src/pocketmine/plugin/PluginManager(157): FolderPluginLoader\FolderPluginLoader->loadPlugin(boolean)
#11 /src/pocketmine/plugin/PluginManager(301): pocketmine\plugin\PluginManager->loadPlugin(boolean)
#12 /devtools插件.phar/src/DevTools/DevTools(32): pocketmine\plugin\PluginManager->loadPlugins(boolean)
#13 /src/pocketmine/plugin/PluginBase(91): DevTools\DevTools->onEnable(boolean)
#14 /src/pocketmine/plugin/PharPluginLoader(128): pocketmine\plugin\PluginBase->setEnabled(boolean)
#15 /src/pocketmine/plugin/PluginManager(567): pocketmine\plugin\PharPluginLoader->enablePlugin(boolean)
#16 /src/pocketmine/Server(2012): pocketmine\plugin\PluginManager->enablePlugin(boolean)
#17 /src/pocketmine/Server(1998): pocketmine\Server->enablePlugin(boolean)
#18 /src/pocketmine/Server(1754): pocketmine\Server->enablePlugins(boolean)
#19 /src/pocketmine/PocketMine(473): pocketmine\Server->__construct(boolean)
#20 (1): (boolean)
#21 (0): {main}(boolean)

ImagicalMine version: 1.0dev #0 [Protocol 38; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT QH-20160128WYZA 6.2 build 9200 (Windows 8 Business Edition) i586
PHP Version: 5.6.4
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
DevTools 1.8.0_bingshen浼樺寲 by PocketMine Team, shoghicp for API(s) 1.0.0
IColor_Chat 1.4.0 by ibook for API(s) 1.0.0
EconomyAPI 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
IMarry 1.0.0 by  for API(s) 1.0.0
IVip 1.0.0 by ibook  for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNoDAAAAAAE=
===END CRASH DUMP===

**Comment by ibookcc** [comment]
And When i del '': float'' on line 22 26 33
Crash agains.
ImagicalMine Crash Dump Fri Mar 11 23:50:50 BNT 2016

Error: syntax error, unexpected ':', expecting ';' or '{'
File: /PureEntities-master/src/milk/pureentities/entity/BaseEntity
Line: 40
Type: E_PARSE

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[31]     public function __destruct(){}
[32] 
[33]     public abstract function updateMove($tickDiff);
[34] 
[35]     public function getSaveId(){
[36]         $class = new \ReflectionClass(get_class($this));
[37]         return $class->getShortName();
[38]     }
[39] 
[40]     public function isMovement() : bool{
[41]         return $this->movement;
[42]     }
[43] 
[44]     public function isFriendly() : bool{
[45]         return $this->friendly;
[46]     }
[47] 
[48]     public function isKnockback() : bool{
[49]         return $this->attackTime > 0;
[50]     }

Backtrace:
#0 /src/pocketmine/Server(0): pocketmine\Server->crashDump(boolean)
#1 /src/spl/BaseClassLoader(13): BaseClassLoader->loadClass(boolean)
#2 /src/spl/BaseClassLoader(13): spl_autoload_call(boolean)
#3 /src/spl/BaseClassLoader(128): (boolean)
#4 /src/spl/BaseClassLoader(13): BaseClassLoader->loadClass(boolean)
#5 /src/spl/BaseClassLoader(13): spl_autoload_call(boolean)
#6 /src/spl/BaseClassLoader(128): (boolean)
#7 /src/spl/BaseClassLoader(26): BaseClassLoader->loadClass(boolean)
#8 /src/spl/BaseClassLoader(26): spl_autoload_call(boolean)
#9 /src/spl/BaseClassLoader(128): (boolean)
#10 /src/pocketmine/entity/Entity(536): BaseClassLoader->loadClass(boolean)
#11 /src/pocketmine/entity/Entity(536): spl_autoload_call(boolean)
#12 /src/pocketmine/entity/Entity(536): ReflectionClass->__construct(boolean)
#13 /PureEntities-master/src/milk/pureentities/PureEntities(79): pocketmine\entity\Entity::registerEntity(boolean)
#14 /devtools插件.phar/src/FolderPluginLoader/FolderPluginLoader(73): milk\pureentities\PureEntities->onLoad(boolean)
#15 /devtools插件.phar/src/FolderPluginLoader/FolderPluginLoader(42): FolderPluginLoader\FolderPluginLoader->initPlugin(boolean)
#16 /src/pocketmine/plugin/PluginManager(157): FolderPluginLoader\FolderPluginLoader->loadPlugin(boolean)
#17 /src/pocketmine/plugin/PluginManager(301): pocketmine\plugin\PluginManager->loadPlugin(boolean)
#18 /devtools插件.phar/src/DevTools/DevTools(32): pocketmine\plugin\PluginManager->loadPlugins(boolean)
#19 /src/pocketmine/plugin/PluginBase(91): DevTools\DevTools->onEnable(boolean)
#20 /src/pocketmine/plugin/PharPluginLoader(128): pocketmine\plugin\PluginBase->setEnabled(boolean)
#21 /src/pocketmine/plugin/PluginManager(567): pocketmine\plugin\PharPluginLoader->enablePlugin(boolean)
#22 /src/pocketmine/Server(2012): pocketmine\plugin\PluginManager->enablePlugin(boolean)
#23 /src/pocketmine/Server(1998): pocketmine\Server->enablePlugin(boolean)
#24 /src/pocketmine/Server(1754): pocketmine\Server->enablePlugins(boolean)
#25 /src/pocketmine/PocketMine(473): pocketmine\Server->__construct(boolean)
#26 (1): (boolean)
#27 (0): {main}(boolean)

ImagicalMine version: 1.0dev #0 [Protocol 38; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT QH-20160128WYZA 6.2 build 9200 (Windows 8 Business Edition) i586
PHP Version: 5.6.4
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
DevTools 1.8.0_bingshen浼樺寲 by PocketMine Team, shoghicp for API(s) 1.0.0
IColor_Chat 1.4.0 by ibook for API(s) 1.0.0
EconomyAPI 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
IMarry 1.0.0 by  for API(s) 1.0.0
IVip 1.0.0 by ibook 淇敼 for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNoDAAAAAAE=
===END CRASH DUMP===

**Comment by ibookcc** [comment]
And When I del ''：bool''on.....
Still Crash
ImagicalMine Crash Dump Fri Mar 11 23:56:32 BNT 2016

Error: syntax error, unexpected ':', expecting ';' or '{'
File: /PureEntities-master/src/milk/pureentities/entity/BaseEntity
Line: 187
Type: E_PARSE

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[178] 
[179]         if($this->attackTime > 0){
[180]             $this->attackTime -= $tickDiff;
[181]         }
[182] 
[183]         Timings::$timerEntityBaseTick->startTiming();
[184]         return $hasUpdate;
[185]     }
[186] 
[187]     public function move($dx, $dy, $dz) : bool{
[188]         Timings::$entityMoveTimer->startTiming();
[189] 
[190]         $movX = $dx;
[191]         $movY = $dy;
[192]         $movZ = $dz;
[193] 
[194]         $list = $this->level->getCollisionCubes($this, $this->level->getTickRate() > 1 ? $this->boundingBox->getOffsetBoundingBox($dx, $dy, $dz) : $this->boundingBox->addCoord($dx, $dy, $dz));
[195]         if($this->isWallCheck()){
[196]             foreach($list as $bb){
[197]                 $dx = $bb->calculateXOffset($this->boundingBox, $dx);

Backtrace:
#0 /src/pocketmine/Server(0): pocketmine\Server->crashDump(boolean)
#1 /src/spl/BaseClassLoader(13): BaseClassLoader->loadClass(boolean)
#2 /src/spl/BaseClassLoader(13): spl_autoload_call(boolean)
#3 /src/spl/BaseClassLoader(128): (boolean)
#4 /src/spl/BaseClassLoader(13): BaseClassLoader->loadClass(boolean)
#5 /src/spl/BaseClassLoader(13): spl_autoload_call(boolean)
#6 /src/spl/BaseClassLoader(128): (boolean)
#7 /src/spl/BaseClassLoader(26): BaseClassLoader->loadClass(boolean)
#8 /src/spl/BaseClassLoader(26): spl_autoload_call(boolean)
#9 /src/spl/BaseClassLoader(128): (boolean)
#10 /src/pocketmine/entity/Entity(536): BaseClassLoader->loadClass(boolean)
#11 /src/pocketmine/entity/Entity(536): spl_autoload_call(boolean)
#12 /src/pocketmine/entity/Entity(536): ReflectionClass->__construct(boolean)
#13 /PureEntities-master/src/milk/pureentities/PureEntities(79): pocketmine\entity\Entity::registerEntity(boolean)
#14 /devtools插件.phar/src/FolderPluginLoader/FolderPluginLoader(73): milk\pureentities\PureEntities->onLoad(boolean)
#15 /devtools插件.phar/src/FolderPluginLoader/FolderPluginLoader(42): FolderPluginLoader\FolderPluginLoader->initPlugin(boolean)
#16 /src/pocketmine/plugin/PluginManager(157): FolderPluginLoader\FolderPluginLoader->loadPlugin(boolean)
#17 /src/pocketmine/plugin/PluginManager(301): pocketmine\plugin\PluginManager->loadPlugin(boolean)
#18 /devtools插件.phar/src/DevTools/DevTools(32): pocketmine\plugin\PluginManager->loadPlugins(boolean)
#19 /src/pocketmine/plugin/PluginBase(91): DevTools\DevTools->onEnable(boolean)
#20 /src/pocketmine/plugin/PharPluginLoader(128): pocketmine\plugin\PluginBase->setEnabled(boolean)
#21 /src/pocketmine/plugin/PluginManager(567): pocketmine\plugin\PharPluginLoader->enablePlugin(boolean)
#22 /src/pocketmine/Server(2012): pocketmine\plugin\PluginManager->enablePlugin(boolean)
#23 /src/pocketmine/Server(1998): pocketmine\Server->enablePlugin(boolean)
#24 /src/pocketmine/Server(1754): pocketmine\Server->enablePlugins(boolean)
#25 /src/pocketmine/PocketMine(473): pocketmine\Server->__construct(boolean)
#26 (1): (boolean)
#27 (0): {main}(boolean)

ImagicalMine version: 1.0dev #0 [Protocol 38; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT QH-20160128WYZA 6.2 build 9200 (Windows 8 Business Edition) i586
PHP Version: 5.6.4
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
DevTools 1.8.0_bingshen浼樺寲 by PocketMine Team, shoghicp for API(s) 1.0.0
IColor_Chat 1.4.0 by ibook for API(s) 1.0.0
EconomyAPI 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
IMarry 1.0.0 by  for API(s) 1.0.0
IVip 1.0.0 by ibook 淇敼 for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNoDAAAAAAE=
===END CRASH DUMP===

**Comment by ibookcc** [comment]
the same bug in G:\Pocket-Mine\MainTest - BackUp - 1\plugins\PureEntities-master\src\milk\pureentities\entity\monster\walking\CaveSpider.php on line 17

**Comment by ibookcc** [comment]
the same bug  in G:\Pocket-Mine\MainTest - BackUp - 1\plugins\PureEntities-master\src\milk\pureentities\entity\monster\WalkingMonster.php on line 26

**Comment by ibookcc** [comment]
the same bug in G:\Pocket-Mine\MainTest - BackUp - 1\plugins\PureEntities-master\src\milk\pureentities\entity\animal\walking\Chicken.php on line 28

**Comment by PoilZero** [comment]
All the files in this directory have an error.
PureEntities-master\src\milk\pureentities\entity\animal\
About '': Float''

**Comment by ibookcc** [comment]
the same bug  in G:\Pocket-Mine\MainTest - BackUp - 1\plugins\PureEntities-master\src\milk\pureentities\entity\animal\WalkingAnimal.php on line 15

**Comment by PoilZero** [comment]
the same error in
PureEntities-master/src/milk/pureentities/entity/BaseEntity.php
PureEntities-master\src\milk\pureentities\entity\monster\walking\CaveSpider.php
PureEntities-master\src\milk\pureentities\entity\monster\WalkingMonster.php
PureEntities-master\src\milk\pureentities\entity\animal\WalkingAnimal.php
The error About '': Float'' or '': bool''

**Comment by PoilZero** [comment]
When I Correct these error.
Running server that it showed  ''ClassNotFoundException: "Class milk\pureentities\entity\float not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144''

**Comment by PoilZero** [comment]
**_I did my best, I really hope that I can help you_** @milk0417 #

**Comment by Erkam246** [comment]
Pls not spamm can you not create a pull request?

**Comment by PoilZero** [comment]
[Uploading Fix some.zip…]()

**Comment by PoilZero** [comment]
What does SPAMM mean.@erkam2002

**Comment by Erkam246** [comment]
-.-

**Comment by LeinneSW** [comment]
please use php7
this isnt error
